riproviamo

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,9 +25,9 @@ jobs:
       run: |
         mkdir -p workspace/base workspace/port
         
-        echo "Scarico la BASE (Evolution X)..."
+        echo "Scarico la BASE (Evolution X con link diretto)..."
         curl -f -L -A "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" \
-          -o workspace/base/base.zip "https://cdn.evolution-x.org/a71/16/EvolutionX-16.0-20260325-a71-11.6.2-Official.zip" || { echo "Errore critico nel download della BASE"; exit 1; }
+          -o workspace/base/base.zip "https://e47b8ab6487c7271956f83661e6ac050.r2.cloudflarestorage.com/evolution-builds/a71/16/EvolutionX-16.0-20260325-a71-11.6.2-Official.zip?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=51584b804f31e3a1037f0d19e1e4742b%2F20260607%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20260607T134002Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Signature=3365c964270d2f9c3748cb2d881eb6d91b70643f761d545b6280371d3d7fbc7b" || { echo "Errore critico nel download della BASE"; exit 1; }
         
         echo "Scarico il PORT (AxionAOSP)..."
         curl -f -L -A "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" \
